version: '3.1'

services:
  database:
    image: mysql:8.0.29
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=delivery-app
    ports:
      - 3306:3306

